pub mod model_funcs;
mod generate_hrd_associated_funcs;
mod errors;

use errors::*;
use generate_hrd_associated_funcs::generate_human_readable_description;
use regex::Regex;
use std::collections::HashMap;
use model_funcs::{filter_stitle, matches_blacklist};
use std::fs::File;
use std::io::{self, BufRead};
use std::path::Path;
use std::sync::mpsc::Sender;

/// A sequence similarity search is executed for a query sequence, which is represented by `Query`.
#[derive(Debug, Clone, Default)]
pub struct Query {
    /// The sequence similarity search results (Blast Hits)
    pub hits: HashMap<String, String>,
    /// A counter of how many times this query was parsed in sequence similarity search results
    pub n_parsed_from_sssr_tables: u16,
}

/// Representation of a query in a sequence similarity search (SSS), e.g. Blast or Diamond.
impl Query {
    /// Returns a new and initialized instance of struct `Query`.
    pub fn new() -> Query {
        Query {
            hits: HashMap::<String, String>::new(),
            n_parsed_from_sssr_tables: 0,
        }
    }

    /// Generates and returns a human readable description (`String`) for this biological query
    /// sequence.
    ///
    /// # Arguments
    ///
    /// * `&self` - A mutable reference to self, this instance of Query
    /// * `split_regex` - A reference to a regular expression used to split descriptions (`stitle`
    ///   in Blast terminology) into words.
    /// * `non_informative_words_regexs` - A reference to a vector holding regular expressions used
    ///   to identify non informative words, that receive only a minimum score.
    /// * `center_at_quantile` - A real value between zero and one used to center the inverse
    ///   information content scores.
    pub fn annotate(
        &self,
        split_regex: &Regex,
        non_informative_words_regexs: &[Regex],
        center_at_quantile: &f64,
    ) -> Option<String> {
        if !self.hits.is_empty() {
            let hit_descriptions: Vec<String> = self
                .hits
                .values()
                .map(|hit_desc| (*hit_desc).clone())
                .collect();
            generate_human_readable_description(
                &hit_descriptions,
                split_regex,
                non_informative_words_regexs,
                center_at_quantile,
            )
        } else {
            None
        }
    }
}

/// Represenation of a set of biological sequences, e.g. a gene family generated by sequence
/// similarity based clustering.
#[derive(Debug, Clone, Default)]
pub struct SeqFamily {
    /// The biological sequence identifiers this SeqFamily comprises:
    pub query_ids: Vec<String>,
    /// Those Query-Identifiers for which all input sequence similarity search result files have
    /// produced data. So in other words those Query-IDs that are ready to be used as input for the
    /// generation of a human readable description:
    pub query_ids_with_complete_data: Vec<usize>,
}

impl SeqFamily {
    /// Creates and empty (`Default::default()`) instance of struct SeqFamily.
    pub fn new() -> SeqFamily {
        Default::default()
    }

    /// Returns `true` if and only if all query identifiers in argument `self.query_ids` are
    /// contained in `self.query_ids_with_complete_data`, false otherwise.
    ///
    /// # Arguments
    ///
    /// * `&self` - a reference to an instance of SeqFamily
    pub fn all_query_data_complete(&self) -> bool {
        (0..(self.query_ids.len()))
            .into_iter()
            .all(|indx| self.query_ids_with_complete_data.contains(&indx))
    }

    /// Stores the information that the Query of argument `query_id` has been parsed completely, so
    /// all of its associated sequence similarity search result data has been successfully read
    /// from the provided input. To implement this the argument `query_id`'s index in the field
    /// `query_ids` is stored in field `query_ids_with_complete_data`.
    ///
    /// # Arguments
    ///
    /// * `&self` - a reference to an instance of SeqFamily
    /// * `query_id: &String` - a reference to the Query Identifier to be marked as successfully
    ///   and completely parsed.
    pub fn mark_query_id_with_complete_data(&mut self, query_id: &String) {
        let query_indx = self
            .query_ids
            .iter()
            .position(|qid| *qid == *query_id)
            .unwrap();
        self.query_ids_with_complete_data.push(query_indx);
    }

    /// Generates and returns a human readable description (`String`) for this set (family) of
    /// biological query sequences.
    ///
    /// # Arguments
    ///
    /// * `&self` - A mutable reference to self, this instance of SeqFamily
    /// * `queries: &HashMap<String, Query>` - A constant reference to the in memory database of
    ///   `Query` instances. This is used to extract the `Hit.description`s from.
    /// * `split_regex` - A reference to a regular expression used to split descriptions (`stitle`
    ///   in Blast terminology) into words.
    /// * `non_informative_words_regexs` - A reference to a vector holding regular expressions used
    ///   to identify non informative words, that receive only a minimum score.
    /// * `center_at_quantile` - A real value between zero and one used to center the inverse
    ///   information content scores.
    pub fn annotate(
        &self,
        queries: &HashMap<String, Query>,
        split_regex: &Regex,
        non_informative_words_regexs: &[Regex],
        center_at_quantile: &f64,
    ) -> Option<String> {
        let mut hit_descriptions: Vec<String> = vec![];
        // Gather all Hit descriptions of all queries belonging to this sequence family. This
        // means collecting all queries' hit-descriptions:
        for qid in self.query_ids.iter() {
            // If the searches found hits of significant similarity for the query sequence:
            if queries.contains_key(qid) {
                for hit_desc in queries.get(qid).unwrap().hits.values() {
                    hit_descriptions.push(hit_desc.clone());
                }
            }
        }
        if !hit_descriptions.is_empty() {
            generate_human_readable_description(
                &hit_descriptions,
                split_regex,
                non_informative_words_regexs,
                center_at_quantile,
            )
        } else {
            None
        }
    }
}

/// Parses a single line read from a respective "gene family input file" (see
/// `parse_seq_families_file`). The argument `family: String` is split into a family identifier
/// (name) and the set of sequence identifiers the family comprises, is made of. Returns a
/// `Result<(String, SeqFamily), std::error::Error>` holding either the parsed gene family or an
/// error.
///
/// # Arguments
///
/// * `family` - The single line (`String`) holding the gene family information
/// * `fam_id_from_gene_id_list_separator` - The character that separates a gene-family's
///   identifier from the list of gene-identifiers the family comprises.
/// * `gene_ids_separator_regex` - The string representation of a regular expression to be used to
///   split the list of gene-identifiers.
pub fn parse_seq_family(
    family: String,
    fam_id_from_gene_id_list_separator: &String,
    gene_ids_separator_regex: &str,
) -> Result<(String, SeqFamily), MalformattedGeneFamilyError> {
    // Split the line by argument `fam_id_from_gene_id_list_separator`. There should be more than 1
    // element (>=2), panic if not:
    let family_cols: Vec<&str> = family
        .trim()
        .split(fam_id_from_gene_id_list_separator)
        .map(|x| x.trim())
        .filter(|x| !x.is_empty())
        .collect();
    if family_cols.len() < 2 {
        return Err(MalformattedGeneFamilyError);
    }

    let seq_fam_name: String = String::from(family_cols[0]); // the family name
    let mut seq_fam_instance = SeqFamily::new(); // the genes contained in that family

    // split the gene column using the default separator.
    // In case genes were separated by a <TAB> character
    // we need to re-join the remaining elements.
    let split_gene_id_list_regex = Regex::new(gene_ids_separator_regex).unwrap();
    let gene_cols: Vec<String> = split_gene_id_list_regex
        .split(&family_cols[1..].join("\t"))
        .map(|x| x.trim().to_string())
        .filter(|x| !x.is_empty())
        .collect();

    // set family genes
    seq_fam_instance.query_ids = gene_cols;
    // return OK
    Ok((seq_fam_name, seq_fam_instance))
}

/// Finds a tabular file (`path`) and parses it in a stream approach, i.e. line by line. Every time
/// an instance of Query is successfully and completely parsed it is send using the argument
/// `transmitter` to the respective registered receiver.
///
/// # Arguments
///
/// * `path: String` - The path to the tabular sequence similarity search result file to parse
/// * `field_separator: char` - The separator to use to split a line into an array of columns
/// * `qacc_col: &usize` - The column index in which to find the `qacc`
/// * `sacc_col: &usize` - The column index in which to find the `sacc`
/// * `stitle_col: &usize` - The column index in which to find the `stitle`
/// * `blacklist_regexs: &Vec<Regex>` - The list of regular expressions used to identify to be
///   discarded descriptions (`stitle`) parsed from the argument `path` sequence similarity search
///   result table.
/// * `filter_regexs: &Vec<Regex>` - The list of regular expressions used to identify to be deleted
///   matching sub-strings in the descriptions (`stitle`) parsed from the argument `path` sequence
///   similarity search result table.
/// * `capture_replace_pairs` - An `Option` of a vector of tuples, pairing a regular expression
///   and the capture-group replacement string. These are iteratively applied and the argument
///   descriptions to prepare it for final splitting into words (see `split_descriptions` for
///   details).
/// * `transmitter: Sender<Query>` - Used to send instances of `Query` to any receiver.
pub fn parse_table(
    path: &String,
    field_separator: &char,
    qacc_col: &usize,
    sacc_col: &usize,
    stitle_col: &usize,
    blacklist_regexs: &[Regex],
    filter_regexs: &[Regex],
    capture_replace_pairs: Option<&Vec<(fancy_regex::Regex, String)>>,
    transmitter: Sender<(String, Query)>,
) {
    let lines =
        read_lines(path).unwrap_or_else(|_| panic!("An error occurred reading file {:?}", &path));
    let mut last_qacc = String::new();
    let mut curr_query = Query::new();
    for line_rslt in lines {
        match line_rslt {
            Ok(line) => {
                let cols: Vec<&str> = line.trim().split(*field_separator).collect();
                let qacc = cols[*qacc_col];
                let sacc = cols[*sacc_col];
                let stitle = cols[*stitle_col];

                if qacc != last_qacc && !last_qacc.is_empty() {
                    transmitter.send((last_qacc, curr_query)).unwrap();
                    curr_query = Query::new();
                }

                if !curr_query.hits.contains_key(sacc)
                    && !matches_blacklist(stitle, blacklist_regexs)
                {
                    let desc = filter_stitle(stitle, filter_regexs, capture_replace_pairs)
                        .trim()
                        .to_lowercase();
                    if !desc.is_empty() {
                        curr_query.hits.insert(sacc.to_string(), desc);
                    }
                }

                last_qacc = qacc.to_string();
            }
            Err(e) => {
                eprintln!(
                    "\nAn error occurred while parsing {:?}:\n{:?}\nContinuing anyway!\n",
                    path, e
                );
            }
        }
    }

    // Send last parsed query. Note this must NOT require `curr_query.hits` to be non-empty:
    // the qacc-change branch above always sends `curr_query` regardless of whether any hits
    // survived blacklist/filtering, so a query whose hits are all blacklisted (e.g. all Hits are
    // "hypothetical protein") must be sent here too, or else it would be silently dropped from
    // the annotation process entirely whenever it happens to be the last query in the file --
    // instead of being registered with zero hits and annotated as "unknown protein" like an
    // otherwise identical query positioned anywhere else in the (sorted) input file:
    if !last_qacc.is_empty() {
        transmitter.send((last_qacc, curr_query)).unwrap();
    }
}

/// The output is wrapped in a Result to allow matching on errors Returns an Iterator to the Reader
/// of the lines of the file.
///
/// # Arguments
///
/// * `filename` The path to the file to open a `BufReader` for.
fn read_lines<P>(filename: P) -> io::Result<io::Lines<io::BufReader<File>>>
where
    P: AsRef<Path>,
{
    let file = File::open(filename)?;
    Ok(io::BufReader::new(file).lines())
}


#[cfg(test)]
mod tests {
    use super::*;
    use crate::default::{
        BLACKLIST_STITLE_REGEXS, FILTER_REGEXS, SPLIT_GENE_FAMILY_GENES_REGEX,
        SPLIT_GENE_FAMILY_ID_FROM_GENE_SET,
    };
    use std::sync::mpsc;

    #[test]
    fn all_query_data_complete_works() {
        let mut sf1 = SeqFamily::new();
        assert!(sf1.all_query_data_complete());
        sf1.query_ids.push("Query1".to_string());
        sf1.query_ids.push("Query2".to_string());
        sf1.query_ids.push("Query3".to_string());
        assert!(!sf1.all_query_data_complete());
        sf1.query_ids_with_complete_data.push(0);
        sf1.query_ids_with_complete_data.push(1);
        assert!(!sf1.all_query_data_complete());
        sf1.query_ids_with_complete_data.push(2);
        assert!(sf1.all_query_data_complete());
    }

    #[test]
    fn mark_query_id_with_complete_data_works() {
        let mut sf1 = SeqFamily::new();
        assert!(sf1.all_query_data_complete());
        sf1.query_ids.push("Query1".to_string());
        sf1.query_ids.push("Query2".to_string());
        sf1.query_ids.push("Query3".to_string());
        assert!(!sf1.all_query_data_complete());
        sf1.mark_query_id_with_complete_data(&"Query1".to_string());
        sf1.mark_query_id_with_complete_data(&"Query2".to_string());
        assert!(!sf1.all_query_data_complete());
        sf1.mark_query_id_with_complete_data(&"Query3".to_string());
        assert!(sf1.all_query_data_complete());
    }

    #[test]
    fn parses_correct_lines_ok() {
        let line_1: String = "OG0023617 VFABAHed036352,VFABAHed036353".to_string();
        let line_2: String =
            "OG0023617  VFABAHed036490 ,     VFABAHed036491  VFABAHed036353  ".to_string();
        let line_3: String = "OG0023617 VFABAHed036352  VFABAHed036353, VFABAHed036354".to_string();

        match parse_seq_family(
            line_1,
            &(*SPLIT_GENE_FAMILY_ID_FROM_GENE_SET).to_string(),
            SPLIT_GENE_FAMILY_GENES_REGEX,
        ) {
            Ok((seq_fam_name, seq_fam_instance)) => {
                assert_eq!(seq_fam_name, "OG0023617");
                assert_eq!(seq_fam_instance.query_ids.len(), 2);
            }
            Err(e) => println!("{}", e),
        }

        match parse_seq_family(
            line_2,
            &(*SPLIT_GENE_FAMILY_ID_FROM_GENE_SET).to_string(),
            SPLIT_GENE_FAMILY_GENES_REGEX,
        ) {
            Ok((seq_fam_name, seq_fam_instance)) => {
                assert_eq!(seq_fam_name, "OG0023617");
                assert_eq!(seq_fam_instance.query_ids.len(), 3);
            }
            Err(e) => println!("{}", e),
        }

        match parse_seq_family(
            line_3,
            &(*SPLIT_GENE_FAMILY_ID_FROM_GENE_SET).to_string(),
            SPLIT_GENE_FAMILY_GENES_REGEX,
        ) {
            Ok((seq_fam_name, seq_fam_instance)) => {
                assert_eq!(seq_fam_name, "OG0023617");
                assert_eq!(seq_fam_instance.query_ids.len(), 3);
            }
            Err(e) => println!("{}", e),
        }
    }

    #[test]
    fn parse_faulty_line_malformatted() {
        let line = "OG0023619|VFABAHed036490,VFABAHed036491".to_string();
        assert!(parse_seq_family(
            line,
            &(*SPLIT_GENE_FAMILY_ID_FROM_GENE_SET).to_string(),
            SPLIT_GENE_FAMILY_GENES_REGEX,
        )
        .is_err())
    }

    // Regression test for a bug where a query was silently dropped -- never sent to the
    // receiver at all -- if (a) every one of its Hit descriptions matched a blacklist regex
    // (e.g. "hypothetical protein") AND (b) it happened to be the last `qacc` block in the
    // input file. Every other position in the file was unaffected by (a) alone, because the
    // qacc-change branch inside the parsing loop always sent the accumulated `curr_query`
    // regardless of whether any of its hits survived blacklist/filtering; only the trailing
    // send after the loop (for the very last query block) additionally required
    // `curr_query.hits` to be non-empty, which an all-blacklisted last query never is. The
    // practical impact: such a query would not even show up as "unknown protein" in the
    // output -- it just vanished, and whether it did so depended purely on its position in
    // the (correctly sorted) input file, not on its data.
    #[test]
    fn parse_table_sends_last_query_even_if_all_its_hits_are_blacklisted() {
        let path = Path::new("misc")
            .join("tmp_test_parse_table_last_query_all_blacklisted.txt")
            .to_str()
            .unwrap()
            .to_string();
        std::fs::write(
            &path,
            concat!(
                "Query1\tHit1\tsome informative kinase domain\n",
                "Query2\tHit2\thypothetical protein\n"
            ),
        )
        .unwrap();

        let (tx, rx) = mpsc::channel();
        parse_table(
            &path,
            &'\t',
            &0,
            &1,
            &2,
            &BLACKLIST_STITLE_REGEXS,
            &FILTER_REGEXS,
            None,
            tx,
        );
        std::fs::remove_file(&path).unwrap();

        let received: HashMap<String, Query> = rx.into_iter().collect();
        assert!(received.contains_key("Query1"));
        // Query2 is the last block in the file and all its hits are blacklisted
        // ("hypothetical protein"); it must still be reported (with zero surviving hits),
        // not silently dropped:
        assert!(received.contains_key("Query2"));
        assert!(received.get("Query2").unwrap().hits.is_empty());
    }
}
